spring:
  application:
    name: weblearning
  datasource:
    url: jdbc:postgresql://localhost:5432/weblearning_db
    username: postgres
    password: 07082004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: YYYRJ4jg1Uqdtv237iYYzss18Aaq1BQ0RQ6IjBCt85U
  expiration: 600000  #10 minutes
  refresh-expiration: 604800000 #7 days

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dd4wtegab}
  api-key: ${CLOUDINARY_API_KEY:212492433566429}
  api-secret: ${CLOUDINARY_API_SECRET:}
