package com.weblearning.service.impl;

import com.weblearning.dto.category.CategoryResponse;
import com.weblearning.entity.Category;
import com.weblearning.repository.CategoryRepository;
import jakarta.persistence.EntityNotFoundException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CategoryServiceImplTest {

    @Mock
    private CategoryRepository categoryRepository;

    @InjectMocks
    private CategoryServiceImpl categoryService;

    @Test
    void createSavesCategory() {
        Category category = new Category();
        category.setName("Programming");
        category.setSlug("programming");

        when(categoryRepository.save(category)).thenReturn(category);

        CategoryResponse result = categoryService.create(category);

        assertNotNull(result);
        assertEquals("Programming", result.getName());
        verify(categoryRepository).save(category);
    }

    @Test
    void getByIdReturnsOptional() {
        Category category = new Category();
        category.setId(1L);

        when(categoryRepository.findById(1L)).thenReturn(Optional.of(category));

        Optional<CategoryResponse> result = categoryService.getById(1L);

        assertEquals(1L, result.orElseThrow().getId());
    }

    @Test
    void getAllReturnsList() {
        when(categoryRepository.findAll()).thenReturn(List.of(new Category()));

        List<CategoryResponse> result = categoryService.getAll();

        assertEquals(1, result.size());
    }

    @Test
    void updateUpdatesFields() {
        Category existing = new Category();
        existing.setId(1L);
        existing.setName("Old");
        existing.setSlug("old");
        existing.setDescription("Old desc");

        Category update = new Category();
        update.setName("New");
        update.setSlug("new");
        update.setDescription("New desc");

        when(categoryRepository.findById(1L)).thenReturn(Optional.of(existing));
        when(categoryRepository.save(existing)).thenReturn(existing);

        CategoryResponse result = categoryService.update(1L, update);

        assertEquals("New", result.getName());
        assertEquals("new", result.getSlug());
        assertEquals("New desc", result.getDescription());
        verify(categoryRepository).save(existing);
    }

    @Test
    void updateThrowsWhenNotFound() {
        when(categoryRepository.findById(1L)).thenReturn(Optional.empty());

        assertThrows(EntityNotFoundException.class, () -> categoryService.update(1L, new Category()));
    }

    @Test
    void deleteDeletesWhenExists() {
        when(categoryRepository.existsById(1L)).thenReturn(true);

        categoryService.delete(1L);

        verify(categoryRepository).deleteById(1L);
    }

    @Test
    void deleteThrowsWhenNotFound() {
        when(categoryRepository.existsById(1L)).thenReturn(false);

        assertThrows(EntityNotFoundException.class, () -> categoryService.delete(1L));
    }

    @Test
    void getByNameReturnsCategory() {
        Category category = new Category();
        category.setName("Design");

        when(categoryRepository.findByName("Design")).thenReturn(Optional.of(category));

        CategoryResponse result = categoryService.getByName("Design");

        assertEquals("Design", result.getName());
    }

    @Test
    void getByNameThrowsWhenNotFound() {
        when(categoryRepository.findByName("Missing")).thenReturn(Optional.empty());

        assertThrows(EntityNotFoundException.class, () -> categoryService.getByName("Missing"));
    }

    @Test
    void createSavesCategoryWithAutoGeneratedSlug() {
        Category category = new Category();
        category.setName("Machine Learning");

        when(categoryRepository.save(category)).thenReturn(category);

        CategoryResponse result = categoryService.create(category);

        assertNotNull(result);
        assertEquals("Machine Learning", result.getName());
        assertEquals("machine-learning", category.getSlug());
        verify(categoryRepository).save(category);
    }

    @Test
    void updatePerformsPartialUpdate() {
        Category existing = new Category();
        existing.setId(1L);
        existing.setName("Old Name");
        existing.setSlug("old-name");
        existing.setDescription("Old Description");

        Category update = new Category();
        update.setDescription("New Description");

        when(categoryRepository.findById(1L)).thenReturn(Optional.of(existing));
        when(categoryRepository.save(existing)).thenReturn(existing);

        CategoryResponse result = categoryService.update(1L, update);

        assertEquals("Old Name", result.getName());
        assertEquals("old-name", result.getSlug());
        assertEquals("New Description", result.getDescription());
        verify(categoryRepository).save(existing);
    }
}

