package com.weblearning.service.impl.admin;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.weblearning.dto.category.CategoryResponse;
import com.weblearning.dto.category.CreateCategoryRequest;
import com.weblearning.dto.category.UpdateCategoryRequest;
import com.weblearning.entity.Category;
import com.weblearning.exception.AlreadyUserException;
import com.weblearning.repository.admin.AdminCategoryRepository;

@ExtendWith(MockitoExtension.class)
class AdminCategoryServiceImplTest {

    @Mock
    private AdminCategoryRepository adminCategoryRepository;

    @InjectMocks
    private AdminCategoryServiceImpl adminCategoryService;

    @Test
    void createCategorySavesWithAutoGeneratedSlug() {
        CreateCategoryRequest request = new CreateCategoryRequest("Machine Learning", null, "ML courses");
        Category category = Category.builder()
                .id(1L)
                .name("Machine Learning")
                .slug("machine-learning")
                .description("ML courses")
                .build();

        when(adminCategoryRepository.existsByName("Machine Learning")).thenReturn(false);
        when(adminCategoryRepository.save(any(Category.class))).thenReturn(category);

        CategoryResponse result = adminCategoryService.createCategory(request);

        assertNotNull(result);
        assertEquals("Machine Learning", result.getName());
        assertEquals("machine-learning", result.getSlug());
        assertEquals("ML courses", result.getDescription());
        verify(adminCategoryRepository).save(any(Category.class));
    }

    @Test
    void createCategoryThrowsWhenExists() {
        CreateCategoryRequest request = new CreateCategoryRequest("Programming", null, "Desc");
        when(adminCategoryRepository.existsByName("Programming")).thenReturn(true);

        assertThrows(AlreadyUserException.class, () -> adminCategoryService.createCategory(request));
    }

    @Test
    void updateCategoryPerformsPartialUpdate() {
        Category existing = Category.builder()
                .id(1L)
                .name("Old Name")
                .slug("old-name")
                .description("Old Description")
                .build();

        UpdateCategoryRequest request = new UpdateCategoryRequest(1L, null, null, "New Description");

        Category updated = Category.builder()
                .id(1L)
                .name("Old Name")
                .slug("old-name")
                .description("New Description")
                .build();

        when(adminCategoryRepository.existsById(1L)).thenReturn(true);
        when(adminCategoryRepository.findById(1L)).thenReturn(Optional.of(existing));
        when(adminCategoryRepository.save(any(Category.class))).thenReturn(updated);

        CategoryResponse result = adminCategoryService.updateCategory(1L, request);

        assertNotNull(result);
        assertEquals("Old Name", result.getName());
        assertEquals("old-name", result.getSlug());
        assertEquals("New Description", result.getDescription());
    }

    @Test
    void updateCategoryUpdatesNameAndRegeneratesSlug() {
        Category existing = Category.builder()
                .id(1L)
                .name("Old Name")
                .slug("old-name")
                .description("Old Description")
                .build();

        UpdateCategoryRequest request = new UpdateCategoryRequest(1L, "New Name", null, null);

        Category updated = Category.builder()
                .id(1L)
                .name("New Name")
                .slug("new-name")
                .description("Old Description")
                .build();

        when(adminCategoryRepository.existsById(1L)).thenReturn(true);
        when(adminCategoryRepository.findById(1L)).thenReturn(Optional.of(existing));
        when(adminCategoryRepository.save(any(Category.class))).thenReturn(updated);

        CategoryResponse result = adminCategoryService.updateCategory(1L, request);

        assertNotNull(result);
        assertEquals("New Name", result.getName());
        assertEquals("new-name", result.getSlug());
        assertEquals("Old Description", result.getDescription());
    }

    @Test
    void updateCategoryThrowsWhenNotFound() {
        UpdateCategoryRequest request = new UpdateCategoryRequest(1L, "New Name", null, null);
        when(adminCategoryRepository.existsById(1L)).thenReturn(false);

        assertThrows(AlreadyUserException.class, () -> adminCategoryService.updateCategory(1L, request));
    }
}
